server:
  port: 8903

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taco_cloud?useSSL=false
    username: postgres
    password: unitech
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # create-drop:应用运行时根据实体创建表格,结束时删除掉对应的表格
      ddl-auto: create-drop
    show-sql: true
