server:
  port: 8903
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springbucks?useSSL=false
    username: postgres
    password: unitech
  jpa:
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # create-drop:程序每次运行时都会根据实体创建表,程序停止运行后会删除对应的表
      ddl-auto: update
    show-sql: true
